### ISSUE TITLE
Quests not showing up

### ISSUE THREAD

**Issue by Slider99** [guiltysyndicate/Unofficial-Quests-For_DayZ-Expansion#1]
Great Idea, hopefully more people contribute to this

**Comment by uswash** [comment]
Added some instructions, sorry for the oversight

**Comment by guiltysyndicate** [comment]
> Added some instructions, sorry for the oversight

Thanks!

**Comment by guiltysyndicate** [comment]
Instructions added, all enabled quests show up now. Updated to the latest expansion version
