### ISSUE TITLE
Peterquests working fine, but since the update(extension) the board not

### ISSUE THREAD

**Issue by Makunia** [guiltysyndicate/Unofficial-Quests-For_DayZ-Expansion#2]
Hey, since the extension update from the quests, the Quest board is not open anymore.

The "Read the Board" comes if you show to it. Then i can click F, animation is start but nothing happing after this.

File:

{
    "ConfigVersion": 1,
    "ID": 5,
    "ClassName": "ExpansionQuestBoardLarge",
    "IsAI": 0,
    "Position": [
        3706.610107421875,
        403.25,
        5983.39990234375
    ],
    "Orientation": [
        170.99000549316407,
        0.0,
        0.0
    ],
    "QuestIDs": [
        800,
        801,
        802,
        803
    ],
    "NPCName": "Quest Board",
    "DefaultNPCText": "There is nothing to do here for you...",
    "Waypoints": [],
    "NPCEmoteID": 46,
    "NPCEmoteIsStatic": 0,
    "NPCLoadoutFile": "",
    "IsStatic": 1
}

**Comment by guiltysyndicate** [comment]
Thanks for the report, I will update and test tonight. Will push resolution

**Comment by guiltysyndicate** [comment]
Resolved

**Comment by guiltysyndicate** [comment]
Resolved, there is an issue with quest 800. Temporarily disabled
